### PR TITLE
add samples for systat 10.2.1

### PR DESCRIPTION
**Pull request by Pitterling**
unfortunately system is quite idle .. therefore the stats are zero .. but it contains the new headers.
once i have better stats i'll push them

### CODE REVIEW

**Comment by Pitterling** [comment]
Network interfaces are shown within Disk Devices section

**Comment by Vest** [comment]
I see this pull request contains the changes from PR #27, does this mean that this PR can be closed?
Thanks

**Comment by Pitterling** [comment]
@Vest  ?? the example datafile this PR has been taken while the system was quiet idle.  Therefore a new file with more realistic data might be appropriate. Why do you ask if this PR can be closed?

**Comment by Vest** [comment]
I probably understood this PR incorrectly, my fault. Do you need samples with the new header **IFACE ...  %ifutil** that can show any activity on the interface?
Probably I can find on one of my servers.

**Comment by Pitterling** [comment]
not only for %ifutil ... having a sar 10.2.1 file from a busy server would be great. Thx

**Pull request merged**
