### PR TITLE
Linux parser seems to be a copy of the AIX parser

### PR DESCRIPTION
**Pull request by Pitterling**
- check for "LINUX RESTART" instead of AIX "UNIX RESTART" messages

### CODE REVIEW

**Comment by Pitterling** [comment]
@vlsi @ynamiki any chance to get this merged?

**Comment by vlsi** [comment]
@Pitterling , do you think this PR deserves a line in `readme.md / Changelog`?
I guess `if (line.contains("LINUX RESTART")) {` might have some user-visible improvement.

**Comment by Pitterling** [comment]
@vlsi no, not necessary. It is just a fix and skips this line for later processing, while the removed lines never came true ..

**Comment by Pitterling** [comment]
@vlsi ready to merge?

**Pull request closed without merging**
