### PR TITLE
add hugepage information - create new statname, but does not graph so…

### PR DESCRIPTION
**Pull request by Pitterling**
… far

- address issue #9

### CODE REVIEW

**Comment by ynamiki** [comment]
@Pitterling Adding the following definition in Linux.xml will show a graph.
Is the output fine with your sar file?

```
            <Graph name="HPAGE" Title="Hugepages" type="unique">
                <Plot Title="Hugepages">
                    <cols>kbhugfree kbhugused</cols>
                    <format base="1024" factor="1024"></format>
                </Plot>
                <Plot Title="%">
                    <cols>%hugused</cols>
                </Plot>
            </Graph>
```

**Comment by Pitterling** [comment]
@ynamiki Thanks for providing the graph definition. Unfortunately my hugepage statistics are always zero. So nothing to show you in the graph ;)

But anyway i will add it to the pull request
capture

**Comment by Pitterling** [comment]
I just found this warning in the debugger console:

> WARN: color not found for tag %hugused
> WARN: color not found for tag kbhugfree
> WARN: color not found for tag kbhugused

**Comment by ynamiki** [comment]
@Pitterling Thanks. A graph with non-zero data written by hand looks good.

The warning indicates that Config.xml should be updated to set color for tag. This is not critical issue since ksar automatically set color.

Config.xml needs overall review (in a new issue): KMmem graph also has the problem.

**Pull request merged**
