### PR TITLE
Fix align the page

### PR DESCRIPTION
**Pull request by ikedaj**
Fix right align the page number when exporting as pdf format.

### CODE REVIEW

**Comment by ikedaj** [comment]
By the way, it would be better if we can choose to insert/not insert the page number into PDF from  "Options" -> "System preferences".
I tried to add the component, but it seems that "Form Editor" is needed.
Do you handle this?

https://github.com/vlsi/ksar/blob/master/src/main/java/net/atomique/ksar/UI/Preferences.java#L71

**Comment by Pitterling** [comment]
@ikedaj - same fix applies for rows 197 & 199. could you add this to your PR?

Regarding the changes to System Preferences: i believe no one from the maintainers uses Netbeans ...  
Personally i never worked with the Forms Editor .. don't know how to handle this.

**Comment by ikedaj** [comment]
Thank you for pointing out that, I added those lines.
As for System Preferences, I'm not good at Netbeans, too...
I'll have to pass on that this time.

**Comment by Pitterling** [comment]
thx for your contribution

**Pull request merged**
